Feat/#6
aldalddl/ServiceAreaParkingLotStatus pull request #19
Opened 2023-11-29 08:31 UTC by aldalddl

### PR 타입
- [ ] 기능 추가
- [ ] 기능 삭제
- [x] 기능 구현 방식 변경
- [ ] 버그 수정
- [ ] 그 외:

### 변경 내용
공공 API로 받아온 JSON 데이터의 key값 변경
한글 -> 영문
### 반영 브랜치
feature/#6 -> develop

2023-11-29 13:23 UTC, ChoiysApple requested changes
잘 수정되었지만, 일부 프로퍼티만 수정되어서 다른 부분도 추가적으로 수정해주세요

2023-11-29 13:23 UTC, ChoiysApple commented on ServiceAreaParkingStatus/Presentation/Main/SearchResultsController.swift
> +    var parkingLotArray = [ParkingModel]()
👍

2023-11-29 13:23 UTC, ChoiysApple commented on ServiceAreaParkingStatus/Presentation/Main/ViewController.swift
> +        self.serviceAreaArray = parking.data.map{ $0.serviceArea }
각자의 스타일이 있지만, 일반적으로 클로저에 사용되는 괄호는 앞뒤를 띄워 주는 것이 일반적입니다. (`SwiftLint` 에서 사용하는 [Kodeco's Swift Style Guide](https://github.com/kodecocodes/swift-style-guide) 기준)
```suggestion
        self.serviceAreaArray = parking.data.map { $0.serviceArea }
```

2023-11-29 13:23 UTC, ChoiysApple commented on ServiceAreaParkingStatus/UseCase/ParkingData.swift
> +    let center: 본부
클래스/구조체와 프로퍼티 명을 영어로 바꾸고 있는 작업이기 때문에, 이 부분에서 사용중인 `노선`, `본부` 자료형도 영어로 바꿔주는 것이 맞아보입니다

2023-12-01 07:08 UTC, aldalddl commented on ServiceAreaParkingStatus/Presentation/Main/ViewController.swift
> +        self.serviceAreaArray = parking.data.map{ $0.serviceArea }
앗 그렇군요, 알려주셔서 감사합니다.
코드 컨벤션 기준을 좀 더 알고 싶었는데 `SwiftLint`를 설치해서 습관을 들여야겠습니다.

2023-12-01 07:12 UTC, aldalddl commented on ServiceAreaParkingStatus/UseCase/ParkingData.swift
> +    let center: 본부
`노선`, `본부`라는 타입을 열거형으로 따로 만들어뒀었는데
불필요한 타입 선언이라고 생각하여 
열거형을 삭제하고, `line`, `center`는 바로 `String`으로 받도록 수정하였습니다.

2023-12-01 14:35 UTC, ChoiysApple approved these changes
SwiftLint의 exclude 부분만 수정하고 머지해주세요

2023-12-02 01:13 UTC, merged